#+TITLE: Sketchfab views tracker
Tracks the view counts of a given set of Sketchfab model pages.
* Configuration
  Copy =sketchfab-views-tracker.sh= wherever you want to keep it.
** =sketchfab-views-tracker.sh=
   Customize the following variables:
   + =pages_to_watch= :: This should point at the filename in which you want to store the list of Sketchfab model pages to watch.  This file must exist.
   + =data_dir=  :: This should point at the directory where you want the resulting data to end up.
** =pages-to-watch.txt= (or whatever file you have =pages_to_watch= point at)
   Every line of =pages-to-watch.txt= (or whatever filename you choose) should contain an address of a Sketchfab model whose views you want to track.  (This repo provides a version of =pages-to-watch.txt= pre-populated with the web addresses of 6 models published by https://sketchfab.com/LivAncWorlds/models.)

   It is safe to add new models at any point.  Deleting a line from this file will not delete any data previously collected. 

